#!/bin/bash
#SBATCH -t 3-00:00:00
#SBATCH --job-name=davis_AlphaFlow

#SBATCH -A def-sushant 

#SBATCH --mail-type=FAIL,ARRAY_TASKS
#SBATCH --mail-user=j.yaacoub@mail.utoronto.ca

#SBATCH --gres=gpu:a100:2
#SBATCH --cpus-per-task=8
#SBATCH --mem=24G
#SBATCH --array=15,17

#SBATCH --output=/home/jyaacoub/projects/def-sushant/jyaacoub/sbatch/out/%x_%a.out

cd /home/jyaacoub/projects/def-sushant/jyaacoub/alphaflow/ 
source .venv-ds/bin/activate

export CUDA_LAUNCH_BLOCKING=1

io_dir="/home/jyaacoub/projects/def-sushant/jyaacoub/data/davis/alphaflow_io/"

world_size=$(nvidia-smi --list-gpus | wc -l)

# modifies .venv-ds/lib/python3.9/site-packages/openfold/model/primitives.py:L47
export DEFAULT_LMA_Q_CHUNK_SIZE=1024 # 1024
export DEFAULT_LMA_KV_CHUNK_SIZE=4096 # 4096
# not used unless we specify --lma

deepspeed --num_gpus $world_size predict_deepspeed.py --world_size $world_size \
    --mode alphafold \
    --input_csv ${io_dir}/input_${SLURM_ARRAY_TASK_ID}.csv \
    --msa_dir ${io_dir}/msa_dir \
    --weights weights/alphaflow_md_distilled_202402.pt \
    --outpdb ${io_dir}/out_pdb_MD-distilled \
    --samples 50 \
    --no_overwrite \
    --chunk_size 2 \
    --low_pres 
    # --cpu_offload