#!/bin/bash
#SBATCH -t 3-00:00:00
#SBATCH --job-name=DG_davis
##SBATCH -d afterok:10246288

#SBATCH -p gpu
#SBATCH -A kumargroup_gpu

#SBATCH --mail-type=ALL
#SBATCH --mail-user=j.yaacoub@mail.utoronto.ca

#SBATCH --gres=gpu:v100:1
#SBATCH --mem=10G
##SBATCH -C gpu32g
#SBATCH --output=/cluster/home/t122995uhn/projects/sbatch/out/%x%A.out

cd /cluster/home/t122995uhn/projects/MutDTA/
                    
source .venv/bin/activate
python train_test.py --model_opt DG --data_opt davis --feature_opt nomsa --edge_opt af2 --batch_size 64 --train
# python test.py -m DG -d PDBbind -f nomsa -e af2 -lr 0.0001 -bs 20 -do 0.4 -ne 2000